import type { IBrand } from "@/type/brand.type";
import { Schema } from "mongoose";

const brandSchema: Schema<IBrand> = new Schema(
  {
    business: { type: Schema.Types.ObjectId, ref: "Business", required: true },
    brand: { type: Schema.Types.ObjectId, ref: "Business", required: true },
    brand_sid: { type: String, unique: true, required: true, match: /^BN[0-9a-fA-F]{32}$/ },
    friendly_name: { type: String, required: true },
    legal_name: { type: String, required: true },
    dba_name: { type: String, default: null },
    business_type: { type: String, required: true },
    industry: { type: String, required: true },
    ein: { type: String, default: null },
    tax_id_type: { type: String, enum: ["EIN", "SSN"], default: null },
    tax_id: { type: String, default: null },
    registration_number: { type: String, default: null },
    registration_country: { type: String, default: "US", required: true },
    registration_state: { type: String, default: null },
    website: { type: String, match: /^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/ },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    street: { type: String, required: true },
    street2: { type: String, default: null },
    city: { type: String, required: true },
    state: { type: String, required: true },
    postal_code: { type: String, required: true },
    country: { type: String, default: "US", required: true },
    status: { type: String, enum: ["draft", "pending", "in_review", "approved", "rejected", "suspended", "expired"], default: "draft" },
    brand_type: { type: String, enum: ["standard", "sole_proprietor", "starter", "low_volume", "high_volume"], default: "standard" },
    submitted_at: { type: Date, default: null },
    approved_at: { type: Date, default: null },
    rejected_at: { type: Date, default: null },
    rejection_reason: { type: String, default: null },
    rejection_code: { type: String, default: null },
    customer_profile_sid: { type: String, match: /^BU[0-9a-fA-F]{32}$/, default: null },
    trust_product_sid: { type: String, match: /^BU[0-9a-fA-F]{32}$/, default: null },
    skip_automatic_sec_vet: { type: Boolean, default: false },
    tcr_brand_id: { type: String, default: null },
    tcr_id: { type: String, default: null },
    brand_score: { type: Number, default: null },
    brand_tier: { type: String, enum: ["T1", "T2", "T3", "unscored"], default: "unscored" },
    identity_status: { type: String, enum: ["not_verified", "pending_verification", "verified", "failed_verification"], default: "not_verified" },
    vetting_status: { type: String, enum: ["not_vetted", "pending_vetting", "vetted", "failed_vetting"], default: "not_vetted" },
    compliance_contact_first_name: { type: String, default: null },
    compliance_contact_last_name: { type: String, default: null },
    compliance_contact_email: { type: String, default: null },
    compliance_contact_phone: { type: String, default: null },
    compliance_contact_job_title: { type: String, default: null },
    description: { type: String, default: null },
    stock_symbol: { type: String, default: null },
    stock_exchange: { type: String, default: null },
    ip_address: { type: String, default: null },
    twilio_response: { type: Schema.Types.Mixed, default: null },
    tcr_response: { type: Schema.Types.Mixed, default: null },
    validation_errors: { type: Schema.Types.Mixed, default: null },
    webhook_events: { type: [Schema.Types.Mixed], default: [] },
  },
  { timestamps: true, toJSON: { virtuals: true, transform: (_doc, ret) => { delete ret.__v; delete ret._id; return ret; } }, toObject: { virtuals: true, transform: (_doc, ret) => { delete ret.__v; delete ret._id; return ret; } } }
);
export { brandSchema };
